#!/usr/bin/env bash

SITE_HOME=site/build/index.html

sbt site && case "$OSTYPE" in
  linux*)   browse ${SITE_HOME} & ;;
  bsd*)     browse ${SITE_HOME} & ;;
  cygwin*)  browse ${SITE_HOME} & ;;
  win*)     start "" ${SITE_HOME} & ;;
  msys*)    start "" ${SITE_HOME} & ;;
  darwin*)  open ${SITE_HOME} & ;; 
  *)        browse ${SITE_HOME} & ;;
esac

