#!/usr/bin/env bash
# Display source code lines statistics
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

cd ${SCRIPT_DIR}/..

echo -e "\n### Files"
echo "* Main: `find  . -name '*.scala' -type f | grep src/main/ | wc -l`"
echo "* Test: `find  . -name '*.scala' -type f | grep src/test/ | wc -l`"
echo "* Docs: `find  docs -name '*.md' -type f | wc -l`"
echo "* Build: `(find . \( -name '*.sbt' \) -type f ; find website/src/components -type f ; cat <<EOF
website/package.json
website/docusaurus.config.js
website/sidebars.js
EOF
) | wc -l`"
echo -e "\n### Lines"
echo "* Main: `find  . -name '*.scala' -type f | grep src/main/ | xargs cat | wc -l`"
echo "* Test: `find  . -name '*.scala' -type f | grep src/test/ | xargs cat | wc -l`"
echo "* Docs: `find  docs -name '*.md' -type f | xargs cat | wc -l`"
echo "* Build: `(find . \( -name '*.sbt' \) -type f ; find website/src/components -type f ; cat <<EOF
website/package.json
website/docusaurus.config.js
website/sidebars.js
EOF
) | xargs cat | wc -l`"
echo

