name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v* ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  build:
    name: Build, Test & Deploy
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 2.13.10, 3.2.2 ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
          key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties')

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
#        run: sbt --client '++${{ matrix.scala }}; test'
        run: sbt --client '++${{ matrix.scala }}; compile'

#      - name: Setup Pages
#        uses: actions/configure-pages@v3
#
      - name: Build site
        run: sbt --client 'site'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
